// <auto-generated />
using System;
using Backend.K02.INFRA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(KigramedDbContext))]
    [Migration("20260517230511_RemoverPedidoAbsorverNaConsulta")]
    partial class RemoverPedidoAbsorverNaConsulta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.K04.DOMAIN.D01.Perfil.PerfilModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("tb01_perfil");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D02.Funcionario.FuncionarioModel", b =>
                {
                    b.Property<string>("Nif")
                        .HasColumnType("text")
                        .HasColumnName("nif");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<int>("Id_Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("id_perfil");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Nif");

                    b.HasIndex("Id_Perfil");

                    b.ToTable("tb02_funcionario");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D03.TipoContacto.TipoContactoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("tb03_tipo_contacto");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D04.Contacto.ContactoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contacto");

                    b.Property<int>("Id_tipo_contacto")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_contacto");

                    b.Property<string>("Nif_cliente")
                        .HasColumnType("text")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Nif_funcionario")
                        .HasColumnType("text")
                        .HasColumnName("nif_funcionario");

                    b.HasKey("Id");

                    b.HasIndex("Id_tipo_contacto");

                    b.HasIndex("Nif_cliente");

                    b.HasIndex("Nif_funcionario");

                    b.ToTable("tb04_contacto");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D05.Auth.AuthModel", b =>
                {
                    b.Property<string>("Nif_funcionario")
                        .HasColumnType("text")
                        .HasColumnName("nif_funcionario");

                    b.Property<string>("Senha_Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_salt");

                    b.Property<string>("Senha_hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.HasKey("Nif_funcionario");

                    b.ToTable("tb05_auth");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D06.Especialidade.EspecialidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("tb06_especialidade");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D07.MedicoEspecialidade.MedicoEspecilidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_especialidade")
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidade");

                    b.Property<string>("Nif_funcionario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nif_funcionario");

                    b.HasKey("Id");

                    b.HasIndex("Id_especialidade");

                    b.HasIndex("Nif_funcionario");

                    b.ToTable("tb07_medico_especialidade");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D08.Servicos.ServicosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Duracao_minuto")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_minuto");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<int>("Id_especialidade")
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric")
                        .HasColumnName("preco");

                    b.HasKey("Id");

                    b.HasIndex("Id_especialidade");

                    b.ToTable("tb08_servico");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D09.Cliente.ClienteModel", b =>
                {
                    b.Property<string>("Nif_cliente")
                        .HasColumnType("text")
                        .HasColumnName("nif");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Nif_cliente");

                    b.ToTable("tb09_cliente");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D09.Genero.GeneroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("tb10_genero");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D11.ClientePaciente.ClientePacienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("tb11_cliente_paciente");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D12.Paciente.PacienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_nascimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<int>("Id_cliente_paciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente_paciente");

                    b.Property<int>("Id_genero")
                        .HasColumnType("integer")
                        .HasColumnName("id_genero");

                    b.Property<string>("Nif_cliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nif_cliente");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Id_cliente_paciente");

                    b.HasIndex("Id_genero");

                    b.HasIndex("Nif_cliente");

                    b.ToTable("tb12_paciente");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D13.EstadoConsulta.EstadoConsultaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("tb13_estado_consulta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Aguarda Pagamento"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Comprovativo Enviado"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Confirmada"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Cancelada"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Finalizada"
                        });
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D14.Pagamento.PagamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoComprovativo")
                        .HasColumnType("text")
                        .HasColumnName("caminho_comprovativo");

                    b.Property<string>("Comprovativo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comprovativo");

                    b.Property<DateTime>("Data_envio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_envio");

                    b.Property<string>("Id_cliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Nif_funcionario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_secretaria");

                    b.HasKey("Id");

                    b.HasIndex("Id_cliente");

                    b.HasIndex("Nif_funcionario");

                    b.ToTable("tb14_pagamento");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D15.Consulta.ConsultaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_consulta")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_consulta");

                    b.Property<int>("Id_estado_consulta")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    b.Property<int>("Id_medico_especialiade")
                        .HasColumnType("integer")
                        .HasColumnName("id_medico_especialista");

                    b.Property<int?>("Id_paciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<int>("Id_servico")
                        .HasColumnType("integer")
                        .HasColumnName("id_servico");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_pedido");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<DateTime?>("PrazoPagamento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("prazo_pagamento");

                    b.HasKey("Id");

                    b.HasIndex("Id_estado_consulta");

                    b.HasIndex("Id_medico_especialiade");

                    b.HasIndex("Id_paciente");

                    b.HasIndex("Id_servico");

                    b.ToTable("tb15_consulta");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D16.Permissao.PermissaoModel", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid_permissoes");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("UUID");

                    b.ToTable("tb16_permissoes");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D17.PerfilPermissao.PerfilPermissaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_perfil")
                        .HasColumnType("integer")
                        .HasColumnName("id_perfil");

                    b.Property<Guid>("UUID_permissao")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid_permissoes");

                    b.HasKey("Id");

                    b.HasIndex("Id_perfil");

                    b.HasIndex("UUID_permissao");

                    b.ToTable("tb17_perfil_permissoes");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D18.PagamentoConsulta.PagamentoConsultaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Consulta")
                        .HasColumnType("integer")
                        .HasColumnName("id_consulta");

                    b.Property<int>("Id_Pagamento")
                        .HasColumnType("integer")
                        .HasColumnName("id_pagamento");

                    b.HasKey("Id");

                    b.HasIndex("Id_Consulta")
                        .IsUnique();

                    b.HasIndex("Id_Pagamento");

                    b.ToTable("tb18_pagamento_consulta");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D19.MedicoConsulta.MedicoConsultaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_consulta")
                        .HasColumnType("integer")
                        .HasColumnName("id_consulta");

                    b.Property<int>("Id_medico_especialidade")
                        .HasColumnType("integer")
                        .HasColumnName("id_medico_especialidade");

                    b.HasKey("Id");

                    b.HasIndex("Id_consulta")
                        .IsUnique();

                    b.HasIndex("Id_medico_especialidade");

                    b.ToTable("tb19_medico_consulta");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D20.SMS.SMSModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_envio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_envio");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("Nif_cliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Nif_funcionario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nif_funcionario");

                    b.HasKey("Id");

                    b.HasIndex("Nif_cliente");

                    b.HasIndex("Nif_funcionario");

                    b.ToTable("tb20_sms");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D02.Funcionario.FuncionarioModel", b =>
                {
                    b.HasOne("Backend.K04.DOMAIN.D01.Perfil.PerfilModel", "Perfil")
                        .WithMany("Funcionarios")
                        .HasForeignKey("Id_Perfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D04.Contacto.ContactoModel", b =>
                {
                    b.HasOne("Backend.K04.DOMAIN.D03.TipoContacto.TipoContactoModel", "TipoContacto")
                        .WithMany("Contactos")
                        .HasForeignKey("Id_tipo_contacto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.K04.DOMAIN.D09.Cliente.ClienteModel", "Cliente")
                        .WithMany("Contactos")
                        .HasForeignKey("Nif_cliente");

                    b.HasOne("Backend.K04.DOMAIN.D02.Funcionario.FuncionarioModel", "Funcionario")
                        .WithMany("Contactos")
                        .HasForeignKey("Nif_funcionario");

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");

                    b.Navigation("TipoContacto");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D05.Auth.AuthModel", b =>
                {
                    b.HasOne("Backend.K04.DOMAIN.D02.Funcionario.FuncionarioModel", "Funcionario")
                        .WithOne("Auth")
                        .HasForeignKey("Backend.K04.DOMAIN.D05.Auth.AuthModel", "Nif_funcionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D07.MedicoEspecialidade.MedicoEspecilidadeModel", b =>
                {
                    b.HasOne("Backend.K04.DOMAIN.D06.Especialidade.EspecialidadeModel", "Especialidade")
                        .WithMany("MedicoEspecialidades")
                        .HasForeignKey("Id_especialidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.K04.DOMAIN.D02.Funcionario.FuncionarioModel", "Funcionario")
                        .WithMany("MedicoEspecialidades")
                        .HasForeignKey("Nif_funcionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D08.Servicos.ServicosModel", b =>
                {
                    b.HasOne("Backend.K04.DOMAIN.D06.Especialidade.EspecialidadeModel", "Especialidade")
                        .WithMany("Servicos")
                        .HasForeignKey("Id_especialidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D12.Paciente.PacienteModel", b =>
                {
                    b.HasOne("Backend.K04.DOMAIN.D11.ClientePaciente.ClientePacienteModel", "ClientePaciente")
                        .WithMany("Pacientes")
                        .HasForeignKey("Id_cliente_paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.K04.DOMAIN.D09.Genero.GeneroModel", "Genero")
                        .WithMany("Pacientes")
                        .HasForeignKey("Id_genero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.K04.DOMAIN.D09.Cliente.ClienteModel", "Cliente")
                        .WithMany("Pacientes")
                        .HasForeignKey("Nif_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ClientePaciente");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D14.Pagamento.PagamentoModel", b =>
                {
                    b.HasOne("Backend.K04.DOMAIN.D09.Cliente.ClienteModel", "Cliente")
                        .WithMany("Pagamentos")
                        .HasForeignKey("Id_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.K04.DOMAIN.D02.Funcionario.FuncionarioModel", "Funcionario")
                        .WithMany("Pagamentos")
                        .HasForeignKey("Nif_funcionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D15.Consulta.ConsultaModel", b =>
                {
                    b.HasOne("Backend.K04.DOMAIN.D13.EstadoConsulta.EstadoConsultaModel", "EstadoConsulta")
                        .WithMany("Consultas")
                        .HasForeignKey("Id_estado_consulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.K04.DOMAIN.D07.MedicoEspecialidade.MedicoEspecilidadeModel", "MedicoEspecialidade")
                        .WithMany("Consultas")
                        .HasForeignKey("Id_medico_especialiade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.K04.DOMAIN.D12.Paciente.PacienteModel", "Paciente")
                        .WithMany("Consultas")
                        .HasForeignKey("Id_paciente");

                    b.HasOne("Backend.K04.DOMAIN.D08.Servicos.ServicosModel", "Servico")
                        .WithMany("Consultas")
                        .HasForeignKey("Id_servico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoConsulta");

                    b.Navigation("MedicoEspecialidade");

                    b.Navigation("Paciente");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D17.PerfilPermissao.PerfilPermissaoModel", b =>
                {
                    b.HasOne("Backend.K04.DOMAIN.D01.Perfil.PerfilModel", "Perfil")
                        .WithMany("PerfisPermissoes")
                        .HasForeignKey("Id_perfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.K04.DOMAIN.D16.Permissao.PermissaoModel", "Permissao")
                        .WithMany("PerfisPermissoes")
                        .HasForeignKey("UUID_permissao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D18.PagamentoConsulta.PagamentoConsultaModel", b =>
                {
                    b.HasOne("Backend.K04.DOMAIN.D15.Consulta.ConsultaModel", "Consulta")
                        .WithOne("PagamentoConsulta")
                        .HasForeignKey("Backend.K04.DOMAIN.D18.PagamentoConsulta.PagamentoConsultaModel", "Id_Consulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.K04.DOMAIN.D14.Pagamento.PagamentoModel", "Pagamento")
                        .WithMany("PagamentoConsultas")
                        .HasForeignKey("Id_Pagamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D19.MedicoConsulta.MedicoConsultaModel", b =>
                {
                    b.HasOne("Backend.K04.DOMAIN.D15.Consulta.ConsultaModel", "Consulta")
                        .WithOne("MedicoConsulta")
                        .HasForeignKey("Backend.K04.DOMAIN.D19.MedicoConsulta.MedicoConsultaModel", "Id_consulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.K04.DOMAIN.D07.MedicoEspecialidade.MedicoEspecilidadeModel", "MedicoEspecialidade")
                        .WithMany("MedicoConsultas")
                        .HasForeignKey("Id_medico_especialidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("MedicoEspecialidade");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D20.SMS.SMSModel", b =>
                {
                    b.HasOne("Backend.K04.DOMAIN.D09.Cliente.ClienteModel", "Cliente")
                        .WithMany("Mensagens")
                        .HasForeignKey("Nif_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.K04.DOMAIN.D02.Funcionario.FuncionarioModel", "Funcionario")
                        .WithMany("Mensagens")
                        .HasForeignKey("Nif_funcionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D01.Perfil.PerfilModel", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("PerfisPermissoes");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D02.Funcionario.FuncionarioModel", b =>
                {
                    b.Navigation("Auth")
                        .IsRequired();

                    b.Navigation("Contactos");

                    b.Navigation("MedicoEspecialidades");

                    b.Navigation("Mensagens");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D03.TipoContacto.TipoContactoModel", b =>
                {
                    b.Navigation("Contactos");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D06.Especialidade.EspecialidadeModel", b =>
                {
                    b.Navigation("MedicoEspecialidades");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D07.MedicoEspecialidade.MedicoEspecilidadeModel", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("MedicoConsultas");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D08.Servicos.ServicosModel", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D09.Cliente.ClienteModel", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("Mensagens");

                    b.Navigation("Pacientes");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D09.Genero.GeneroModel", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D11.ClientePaciente.ClientePacienteModel", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D12.Paciente.PacienteModel", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D13.EstadoConsulta.EstadoConsultaModel", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D14.Pagamento.PagamentoModel", b =>
                {
                    b.Navigation("PagamentoConsultas");
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D15.Consulta.ConsultaModel", b =>
                {
                    b.Navigation("MedicoConsulta")
                        .IsRequired();

                    b.Navigation("PagamentoConsulta")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.K04.DOMAIN.D16.Permissao.PermissaoModel", b =>
                {
                    b.Navigation("PerfisPermissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
